type RaiseProsalPreview {
  organizationName: String!
  organizationType: String!
  cover: String!
  logo: String!
  tokenTicker: String!
  details: RaiseProposalDetails!
  display: Boolean!
}

type RaiseProposalDetails {
  shortDesc: String!
  website: String!
  telegram: String!
  discord: String!
  twitter: String!
  medium: String!
  whitepaper: String!
  deepdive: String!

  tokenAddress: String!
  tokenName: String!
  tokenTotalSupply: Float!
  tokenIcon: String!
  tokenFixedSuplly: Boolean!
  tokenTotalRaised: Int!

  totalRaised: Int!
  
  mode: String!
  totalForSale: Int!
  range: Int!
  offset: Float!
  factor: Float!

  raisingComponentAddress: String!
  votingComponentAddress: String!
}

type Query {
  allRaiseProposalPreviews: [RaiseProsalPreview!]
  previewsByDisplayFlag(display: Boolean!): [RaiseProsalPreview!]
}
